CoreAndFood/Models/Category.cs
using System.ComponentModel.DataAnnotations;

namespace CoreAndFood.Models
{
	public class Category
	{
		public int CategoryId { get; set; }
		[Required(ErrorMessage = "Category Name not be empty")]
		[StringLength(20, ErrorMessage = "Please only enter 4-20 characters", MinimumLength = 4)]
		public string? CategoryName { get; set; }
		public string? CategoryDescription { get; set; }
		public bool Status { get; set; }
		public List<Food> Foods { get; set; }


	}
}

CoreAndFood/Models/Context.cs
using Microsoft.EntityFrameworkCore;

namespace CoreAndFood.Models
{
    public class Context : DbContext
    {
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer("server=DESKTOP-H6BPHOP\\SQLEXPRESS; database=CoreAndFood;integrated security=true;TrustServerCertificate=True");
        }
        public DbSet<Food> Foods { get; set; }
        public DbSet<Category> Categories { get; set; }
    }
}

CoreAndFood/Models/ErrorViewModel.cs
namespace CoreAndFood.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CoreAndFood/Models/Food.cs
namespace CoreAndFood.Models;

public class Food
{
    public int FoodId { get; set; }
    public string? Name { get; set; }
    public string? Description { get; set; }
    public double Price { get; set; }
    public string? ImageURL { get; set; }

    public int Stock { get; set; }

    public int CategoryId { get; set; }
    public virtual Category Category { get; set; } //ilişkiyi kurabilmek için
}

CoreAndFood/Controllers/CategoryController.cs
using CoreAndFood.Repositories;
using Microsoft.AspNetCore.Mvc;
using CoreAndFood.Models;
namespace CoreAndFood.Controllers
{
	public class CategoryController : Controller
	{
		CategoryRepository categoryRepository = new CategoryRepository();
		public IActionResult Index()
		{	
			return View(categoryRepository.TList());
		}
		[HttpGet]
		public IActionResult CategoryAdd()
		{
			return View();
		}
		[HttpPost]
		public IActionResult CategoryAdd(Category cat)
		{
			if (!ModelState.IsValid)
			{
				return View("CategoryAdd");
			}
			categoryRepository.TAdd(cat);
			return RedirectToAction("Index");
		}
		public IActionResult CategoryGet(int id)
		{
			var x =categoryRepository.getT(id);
			Category ct = new Category()
			{
				CategoryName = x.CategoryName,
				CategoryDescription = x.CategoryDescription,
				CategoryId = x.CategoryId
			};
			return View(x);
		}
		[HttpPost]
		public IActionResult CategoryUpdate(Category ct)
		{	
			var x= categoryRepository.getT(ct.CategoryId);
			x.CategoryName = ct.CategoryName;
			x.CategoryDescription = ct.CategoryDescription;
			x.Status = true;
			categoryRepository.TUpdate(x);
			return RedirectToAction("Index");
		}
        public IActionResult CategoryDelete(int id)
		{
			var x = categoryRepository.getT(id);
			x.Status=false;
			categoryRepository.TUpdate(x);
			return RedirectToAction("Index");
		}

    }
}

CoreAndFood/Controllers/FoodController.cs
using CoreAndFood.Models;
using CoreAndFood.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using X.PagedList;

namespace CoreAndFood.Controllers
{
	public class FoodController : Controller
	{
		Context c = new Context();
		FoodRepository foodRepository = new FoodRepository();
		public IActionResult Index(int page=1)
		{
			return View(foodRepository.TList("Category").ToPagedList(page,5));
		}
		[HttpGet]
		public IActionResult FoodAdd()
		{
			List<SelectListItem> values = (from x in c.Categories.ToList()
										   select new SelectListItem
										   {
											   Text = x.CategoryName,
											   Value = x.CategoryId.ToString()
										   }).ToList();
			ViewBag.V = values;
			return View();
		}
		[HttpPost]
		public IActionResult FoodAdd(Food f)
		{
			foodRepository.TAdd(f);
			return RedirectToAction("Index");
		}
		public IActionResult FoodDelete(int id)
		{
			foodRepository.TRemove(new Food { FoodId = id });
			return RedirectToAction("Index");
		}
		public IActionResult FoodGet(int id)
		{
			List<SelectListItem> values = (from y in c.Categories.ToList()
										   select new SelectListItem
										   {
											   Text = y.CategoryName,
											   Value = y.CategoryId.ToString()
										   }).ToList();
			ViewBag.V = values;

			var x = foodRepository.getT(id);
			
		Food f = new Food()
			{	
				FoodId = x.FoodId,
				CategoryId = x.CategoryId,
				Name = x.Name,
				Price = x.Price,
				Stock = x.Stock,
				Description = x.Description,
				ImageURL = x.ImageURL
			};
			return View(x);
		}
		public IActionResult FoodUpdate(Food f)
		{
			foodRepository.TUpdate(f);
			return RedirectToAction("Index");
		}

	}
}

CoreAndFood/Controllers/HomeController.cs
using CoreAndFood.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CoreAndFood.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

CoreAndFood/Views/Category/CategoryAdd.cshtml
@model CoreAndFood.Models.Category
@{
}

<h2>Category Add Page</h2>
<br />
@using (Html.BeginForm("CategoryAdd", "Category", FormMethod.Post))
{
    <b>Category Name</b>
    @Html.TextBoxFor(x => x.CategoryName, new { @class = "form-control" })
    @Html.ValidationMessageFor(x=>x.CategoryName,"",new {@style= "color:red"})
    <br />
    <b>Category Descriptrion</b>
    @Html.TextBoxFor(x => x.CategoryDescription, new { @class = "form-control" })
    <br />
    <button class="btn btn-primary">save</button>

}

CoreAndFood/Views/Category/CategoryGet.cshtml
@model CoreAndFood.Models.Category

<h2>Category Add Page</h2>
<br />
@using (Html.BeginForm("CategoryUpdate", "Category", FormMethod.Post))
{
    <b>Category Id</b>
    @Html.TextBoxFor(x => x.CategoryId, new { @class = "form-control" })
    <br />
    <b>Category Name</b>
    @Html.TextBoxFor(x => x.CategoryName, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.CategoryName, "", new { @style = "color:red" })
    <br />
    <b>Category Descriptrion</b>
    @Html.TextBoxFor(x => x.CategoryDescription, new { @class = "form-control" })
    <br />
    <button class="btn btn-warning">Update</button>

}

CoreAndFood/Views/Category/Index.cshtml
@model List<CoreAndFood.Models.Category>
@{
    }

<h2>Category list</h2>

<table class="table table-bordered">
    <tr>
        <td>Id</td>
        <td>Category Name</td>
        <td>Status</td>
        <td>Delete</td>
        <td>Update</td>
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.CategoryId</td>
            <td>@x.CategoryName</td>
            <td>@x.Status</td>
            <td><a asp-controller="Category" asp-action="CategoryDelete" asp-route-id="@x.CategoryId" class="btn btn-danger">Delete</a></td>
            <td><a asp-controller="Category" asp-action="CategoryGet" asp-route-id="@x.CategoryId" class="btn btn-success">Update</a></td>
        </tr>
    }
</table>
<a asp-controller="Category" asp-action="CategoryAdd" class="btn btn-primary">New Category</a>

CoreAndFood/Views/Food/FoodAdd.cshtml
@model CoreAndFood.Models.Food

<h2>Food Add Page</h2>

@using (Html.BeginForm("FoodAdd", "Food", FormMethod.Post))
{
    <b>Food Name</b>
    @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
    <br />

    <b>Food Price</b>
    @Html.TextBoxFor(x => x.Price, new { @class = "form-control" })
    <br />
    <b>Food ImageURL</b>
    @Html.TextBoxFor(x => x.ImageURL, new { @class = "form-control" })
    <br />
    <b>Stock</b>
    @Html.TextBoxFor(x => x.Stock, new { @class = "form-control" })
    <br />
    <b>Category</b>
    @Html.DropDownListFor(x => x.CategoryId, (List<SelectListItem>)ViewBag.V, new { @class = "form-control" })
    <br />
    <b>Food Descriptrion</b>
    @Html.TextAreaFor(x => x.Description, new { @class = "form-control" })
    <br />
    <button class="btn btn-primary">save</button>

}

CoreAndFood/Views/Food/FoodGet.cshtml
@model CoreAndFood.Models.Food
<h2>Food Add Page</h2>

@using (Html.BeginForm("FoodUpdate", "Food", FormMethod.Post))
{
    <b>Food Id</b>
    @Html.TextBoxFor(x => x.FoodId, new { @class = "form-control" })
    <br />

    <b>Food Name</b>
    @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
    <br />

    <b>Food Price</b>
    @Html.TextBoxFor(x => x.Price, new { @class = "form-control" })
    <br />

    <b>Food ImageURL</b>
    @Html.TextBoxFor(x => x.ImageURL, new { @class = "form-control" })
    <br />

    <b>Stock</b>
    @Html.TextBoxFor(x => x.Stock, new { @class = "form-control" })
    <br />

    <b>Category</b>
    @Html.DropDownListFor(x => x.CategoryId, (List<SelectListItem>)ViewBag.V, new { @class = "form-control" })
    <br />

    <b>Food Descriptrion</b>
    @Html.TextAreaFor(x => x.Description, new { @class = "form-control" })
    <br />

    <button class="btn btn-primary">save</button>

}

CoreAndFood/Views/Food/Index.cshtml
@using X.PagedList
@using X.PagedList.Mvc.Core
@model IPagedList<CoreAndFood.Models.Food>
@{
}

<h2>Food List</h2>

<table class="table table-bordered">
    <tr>
        <td>ID</td>
        <td>Food Name</td>
        <td>Price</td>
        <td>Stock</td>
        <td>Category Name</td>
        <td>Delete</td>
        <td>Update</td>
        <td>Details</td>
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.FoodId</td>
            <td>@x.Name</td>
            <td>@x.Price</td>
            <td>@x.Stock</td>
            <td>@x.Category.CategoryName</td>
            <td><a asp-controller="Food" asp-action="FoodDelete" asp-route-id="@x.FoodId" class="btn btn-danger">Delete</a></td>
            <td><a asp-controller="Food" asp-action="FoodGet" asp-route-id="@x.FoodId" class="btn btn-success">Update</a></td>
            <td><a href="#" class="btn btn-info">Details</a></td>
        </tr>
    }
</table>

@Html.PagedListPager((IPagedList)Model,page=>Url.Action("Index",new {page}))

<a asp-controller="Food" asp-action="FoodAdd" class="btn btn-primary">New Food</a>

CoreAndFood/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CoreAndFood/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>

    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">Core And Food</a>
            </div>
            <ul class="nav navbar-nav">
                <li><a asp-controller="Category" asp-action="Index">Category</a></li>
                <li><a asp-controller="Food" asp-action="Index">Food</a></li>
                <li><a href="#">Google Chart</a></li>
                <li><a href="#">Popup</a></li>
                <li><a href="#">Statistics</a></li>
                <li><a href="#">Settings</a></li>
                <li><a href="#">Log out</a></li>
            </ul>
        </div>
    </nav>

    <div class="container">
        @RenderBody()
    </div>

</body>
</html>